/**
 * Puzzle Index — Provides all puzzles and chapter groupings.
 *
 * Reads puzzle specs from generated.ts (auto-generated by scripts/generate_chapters.js)
 * and builds Puzzle objects using buildPuzzleFromSpec.
 */

import { Puzzle, Chapter } from '../types';
import { buildPuzzleFromSpec } from '../puzzleBuilder';
import { allChapterSpecs, chapterGroups } from './generated';

// Build all puzzles from specs
export const allPuzzles: Puzzle[] = allChapterSpecs.map(spec => buildPuzzleFromSpec(spec));

// Export chapters (groupings for UI)
export const chapters: Chapter[] = chapterGroups.map(g => ({
    id: g.puzzleIds[0] || 'unknown',
    title: g.title,
    subtitle: g.subtitle,
    puzzleIds: g.puzzleIds,
}));

// Lookup helper
export function getPuzzleById(id: string): Puzzle | undefined {
    return allPuzzles.find(p => p.id === id);
}
