/**
 * Puzzle Index — Provides all puzzles and chapter groupings.
 *
 * Reads puzzle specs from generated.ts (auto-generated by scripts/generate_chapters.js)
 * and generated_new.ts (auto-generated by scripts/generate_levels.js)
 * and builds Puzzle objects using buildPuzzleFromSpec.
 */

import { Puzzle, Chapter } from '../types';
import { buildPuzzleFromSpec } from '../puzzleBuilder';
import { allChapterSpecs, chapterGroups } from './generated';
import { allNewSpecs, newChapterGroups } from './generated_new';

// Build all puzzles from specs (original + generated)
const allSpecs = [...allChapterSpecs, ...allNewSpecs];
export const allPuzzles: Puzzle[] = allSpecs.map(spec => buildPuzzleFromSpec(spec));

// Export chapters (groupings for UI)
const allGroups = [...chapterGroups, ...newChapterGroups];
export const chapters: Chapter[] = allGroups.map(g => ({
    id: g.puzzleIds[0] || 'unknown',
    title: g.title,
    subtitle: g.subtitle,
    puzzleIds: g.puzzleIds,
}));

// Lookup helper
export function getPuzzleById(id: string): Puzzle | undefined {
    return allPuzzles.find(p => p.id === id);
}
